services:
  lava-test-server:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64  # Force amd64 platform regardless of host architecture
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0:8080
      - DATABASE_URL=sqlite:/app/data/tests.db
    volumes:
      - /tmp/lava-cli:/tmp/lava-cli
      - ./data:/app/data
    restart: unless-stopped 